apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-backend
spec:
  selector:
    matchLabels:
      app: order-backend
  template:
    metadata:
      labels:
        app: order-backend
    spec:
      containers:
        - name: order-backend
          image: kxingjing/order-backend:1.0
          resources:
            limits:
              memory: "1024Mi"
              cpu: "500m"
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: order-backend
spec:
  type: ClusterIP
  selector:
    app: order-backend
  ports:
    - port: 80
      targetPort: 5000
